### ISSUE TITLE
Merge with similar lists

### ISSUE THREAD

**Issue by jimbobbennett** [XamSome/awesome-xamarin#35]
It would be good to merge this with https://github.com/MarcBruins/awesome-xamarin

**Comment by MarcBruins** [comment]
We could make a github organization where we are both owners and merge them there. After that we can point both repos to the one under the organization. What do you think?

**Comment by benoitjadinon** [comment]
so we'll both lose the stars... but it would be fairer than our original non-agreement ;)

**Comment by benoitjadinon** [comment]
maybe moving one project to the org will keep the stars, then we'll merge the other in it

**Comment by benoitjadinon** [comment]
and by stars I mean actual people who registered to get notified of changes, it would be nice for them not to get lost

**Comment by orestesgaolin** [comment]
Perhaps set one repository to track/mirror README.md in other?

**Comment by luismts** [comment]
When I created I didn't see anything like this. In my case, it's more general 

https://github.com/xamarinuniverse/XamarinUniversalLibrary

**Comment by benoitjadinon** [comment]
done
