### ISSUE TITLE
Suggestion: JSX for Xamarin Forms - Web Atoms

### ISSUE THREAD

**Issue by ackava** [XamSome/awesome-xamarin#84]
https://www.webatoms.in - JSX for Xamarin Forms

"Web Atoms" is an advanced MVVM framework to write cross platform applications in HTML5 and Xamarin.Forms. Web Atoms allows you to create Xamarin Forms app in JSX/JavaScript along with C#. Web Atoms allows use of both NPM and NuGet. Hosting JSX/JavaScript on web server allows you to quickly update the apps quickly with Code Push and it also allows you to distribute side by side versions of the same app. Using JavaScript modules, you can divide large app into smaller modules, also offer localization using modules with reduced app size.

**Comment by Sarthak261995** [comment]
@ackava you can edit readme and generate PR

**Comment by benoitjadinon** [comment]
thx, closed by #89
